// FRPB — utils/android-models.ts
// Brand-agnostic model registry + USB vendor-ID → brand mapping used by the
// ADB/USB device engine. This is the single source of truth for the model
// dropdown and for the USB-fallback brand detection. There are deliberately
// NO per-brand code paths anywhere in the engine — every Android device flows
// through the same ADB-based pipeline.

export const ANDROID_VENDOR_IDS: Record<number, string> = {
  0x04e8: "Samsung",
  0x18d1: "Google",
  0x22d9: "OnePlus", // shared VID used by OnePlus / Oppo family devices
  0x2717: "Xiaomi",
  0x12d1: "Huawei",
  0x22b8: "Motorola",
  0x1004: "LG",
  0x054c: "Sony",
  0x0bb4: "HTC",
  0x2d95: "Vivo",
  0x2a70: "Realme",
  0x0e8d: "MediaTek",
  0x05c6: "Qualcomm",
};

/**
 * Map a USB vendor ID to a friendly brand name. Returns `undefined` for any
 * unrecognized VID — callers then report "Android device" (never exclude a
 * brand).
 */
export function brandFromVendorId(vendorId: number): string | undefined {
  return ANDROID_VENDOR_IDS[vendorId];
}

// ─── Curated, brand-agnostic model registry ─────────────────────────────────
// A wide cross-section of current and recent Android models so the UI can offer
// a sensible pick list. Manual entry is always allowed regardless of this list.
const KNOWN_MODELS: string[] = [
  // Samsung Galaxy S series
  "Samsung Galaxy S20",
  "Samsung Galaxy S20 FE",
  "Samsung Galaxy S21",
  "Samsung Galaxy S21 FE",
  "Samsung Galaxy S21 Ultra",
  "Samsung Galaxy S22",
  "Samsung Galaxy S22 Ultra",
  "Samsung Galaxy S23",
  "Samsung Galaxy S23 FE",
  "Samsung Galaxy S23 Ultra",
  "Samsung Galaxy S24",
  "Samsung Galaxy S24 FE",
  "Samsung Galaxy S24 Ultra",
  "Samsung Galaxy S25",
  "Samsung Galaxy S25 Ultra",
  // Samsung Galaxy A series
  "Samsung Galaxy A03",
  "Samsung Galaxy A04",
  "Samsung Galaxy A05",
  "Samsung Galaxy A06",
  "Samsung Galaxy A10",
  "Samsung Galaxy A11",
  "Samsung Galaxy A12",
  "Samsung Galaxy A13",
  "Samsung Galaxy A14",
  "Samsung Galaxy A15",
  "Samsung Galaxy A20",
  "Samsung Galaxy A21",
  "Samsung Galaxy A22",
  "Samsung Galaxy A23",
  "Samsung Galaxy A24",
  "Samsung Galaxy A25",
  "Samsung Galaxy A30",
  "Samsung Galaxy A31",
  "Samsung Galaxy A32",
  "Samsung Galaxy A33",
  "Samsung Galaxy A34",
  "Samsung Galaxy A35",
  "Samsung Galaxy A50",
  "Samsung Galaxy A51",
  "Samsung Galaxy A52",
  "Samsung Galaxy A53",
  "Samsung Galaxy A54",
  "Samsung Galaxy A55",
  "Samsung Galaxy A70",
  "Samsung Galaxy A71",
  "Samsung Galaxy A72",
  "Samsung Galaxy A73",
  // Samsung Galaxy M series
  "Samsung Galaxy M12",
  "Samsung Galaxy M13",
  "Samsung Galaxy M14",
  "Samsung Galaxy M15",
  "Samsung Galaxy M21",
  "Samsung Galaxy M31",
  "Samsung Galaxy M32",
  "Samsung Galaxy M33",
  "Samsung Galaxy M34",
  "Samsung Galaxy M35",
  "Samsung Galaxy M51",
  "Samsung Galaxy M53",
  "Samsung Galaxy M54",
  // Samsung Galaxy Z + Note
  "Samsung Galaxy Z Flip 3",
  "Samsung Galaxy Z Flip 4",
  "Samsung Galaxy Z Flip 5",
  "Samsung Galaxy Z Flip 6",
  "Samsung Galaxy Z Fold 3",
  "Samsung Galaxy Z Fold 4",
  "Samsung Galaxy Z Fold 5",
  "Samsung Galaxy Z Fold 6",
  "Samsung Galaxy Note 10",
  "Samsung Galaxy Note 10+",
  "Samsung Galaxy Note 20",
  "Samsung Galaxy Note 20 Ultra",
  // Xiaomi + Redmi + POCO
  "Xiaomi Redmi 9",
  "Xiaomi Redmi 9A",
  "Xiaomi Redmi 9C",
  "Xiaomi Redmi 9T",
  "Xiaomi Redmi 10",
  "Xiaomi Redmi 10A",
  "Xiaomi Redmi 10C",
  "Xiaomi Redmi 11",
  "Xiaomi Redmi 12",
  "Xiaomi Redmi 13",
  "Xiaomi Redmi 14",
  "Xiaomi Redmi Note 9",
  "Xiaomi Redmi Note 10",
  "Xiaomi Redmi Note 11",
  "Xiaomi Redmi Note 12",
  "Xiaomi Redmi Note 13",
  "Xiaomi Redmi Note 14",
  "Xiaomi 11",
  "Xiaomi 11 Lite",
  "Xiaomi 12",
  "Xiaomi 13",
  "Xiaomi 14",
  "Xiaomi POCO X3",
  "Xiaomi POCO X4",
  "Xiaomi POCO X5",
  "Xiaomi POCO X6",
  "Xiaomi POCO M3",
  "Xiaomi POCO M4",
  "Xiaomi POCO M5",
  "Xiaomi POCO F3",
  "Xiaomi POCO F4",
  "Xiaomi POCO F5",
  "Xiaomi POCO F6",
  // OnePlus
  "OnePlus 8",
  "OnePlus 8 Pro",
  "OnePlus 8T",
  "OnePlus 9",
  "OnePlus 9 Pro",
  "OnePlus 9R",
  "OnePlus 10 Pro",
  "OnePlus 10T",
  "OnePlus 11",
  "OnePlus 11R",
  "OnePlus 12",
  "OnePlus 12R",
  "OnePlus Nord",
  "OnePlus Nord 2",
  "OnePlus Nord CE",
  "OnePlus Nord CE 3",
  "OnePlus Nord N30",
  // Oppo
  "Oppo A15",
  "Oppo A16",
  "Oppo A17",
  "Oppo A18",
  "Oppo A38",
  "Oppo A58",
  "Oppo A78",
  "Oppo A98",
  "Oppo Reno 8",
  "Oppo Reno 8T",
  "Oppo Reno 10",
  "Oppo Reno 11",
  "Oppo Reno 12",
  "Oppo F21 Pro",
  "Oppo F23",
  // Vivo
  "Vivo Y15",
  "Vivo Y16",
  "Vivo Y17",
  "Vivo Y21",
  "Vivo Y22",
  "Vivo Y27",
  "Vivo Y33",
  "Vivo Y36",
  "Vivo Y55",
  "Vivo Y73",
  "Vivo V23",
  "Vivo V25",
  "Vivo V27",
  "Vivo V29",
  "Vivo X60",
  "Vivo X70",
  "Vivo X80",
  "Vivo X90",
  // Realme
  "Realme 5",
  "Realme 6",
  "Realme 7",
  "Realme 8",
  "Realme 9",
  "Realme 10",
  "Realme 11",
  "Realme 12",
  "Realme 13",
  "Realme C11",
  "Realme C21",
  "Realme C25",
  "Realme C30",
  "Realme C33",
  "Realme C35",
  "Realme C51",
  "Realme C53",
  "Realme C55",
  "Realme Narzo 50",
  "Realme Narzo 60",
  "Realme Narzo 70",
  "Realme GT 5",
  "Realme GT 6",
  // Motorola
  "Motorola Moto G4",
  "Motorola Moto G5",
  "Motorola Moto G6",
  "Motorola Moto G7",
  "Motorola Moto G8",
  "Motorola Moto G9",
  "Motorola Moto G10",
  "Motorola Moto G20",
  "Motorola Moto G30",
  "Motorola Moto G40",
  "Motorola Moto G50",
  "Motorola Moto G60",
  "Motorola Moto G70",
  "Motorola Moto G80",
  "Motorola Moto G82",
  "Motorola Moto G84",
  "Motorola Moto G85",
  "Motorola Moto G100",
  "Motorola Moto G200",
  "Motorola Moto E5",
  "Motorola Moto E6",
  "Motorola Moto E7",
  "Motorola Moto E13",
  "Motorola Moto E32",
  "Motorola Moto E40",
  "Motorola Edge 20",
  "Motorola Edge 30",
  "Motorola Edge 40",
  "Motorola Edge 50",
  "Motorola Razr",
  "Motorola Razr 2023",
  // Nokia
  "Nokia 1.3",
  "Nokia 1.4",
  "Nokia 2.3",
  "Nokia 2.4",
  "Nokia 3.1",
  "Nokia 3.2",
  "Nokia 3.4",
  "Nokia 5.1",
  "Nokia 5.3",
  "Nokia 5.4",
  "Nokia 6.1",
  "Nokia 6.2",
  "Nokia 7.1",
  "Nokia 7.2",
  "Nokia 8.1",
  "Nokia 8.3",
  "Nokia 9",
  "Nokia G10",
  "Nokia G11",
  "Nokia G20",
  "Nokia G21",
  "Nokia G22",
  "Nokia G42",
  "Nokia G50",
  "Nokia G60",
  "Nokia X10",
  "Nokia X20",
  // Google Pixel
  "Google Pixel 3",
  "Google Pixel 3a",
  "Google Pixel 4",
  "Google Pixel 4a",
  "Google Pixel 5",
  "Google Pixel 5a",
  "Google Pixel 6",
  "Google Pixel 6a",
  "Google Pixel 6 Pro",
  "Google Pixel 7",
  "Google Pixel 7a",
  "Google Pixel 7 Pro",
  "Google Pixel 8",
  "Google Pixel 8a",
  "Google Pixel 8 Pro",
  "Google Pixel 9",
  "Google Pixel 9 Pro",
  "Google Pixel Fold",
  // Honor
  "Honor 8A",
  "Honor 8S",
  "Honor 9A",
  "Honor 9X",
  "Honor 10",
  "Honor 20",
  "Honor 50",
  "Honor 50 Lite",
  "Honor 70",
  "Honor 90",
  "Honor 90 Lite",
  "Honor X7",
  "Honor X8",
  "Honor X9",
  "Honor X9a",
  "Honor X9b",
  // Infinix
  "Infinix Hot 9",
  "Infinix Hot 10",
  "Infinix Hot 11",
  "Infinix Hot 12",
  "Infinix Hot 20",
  "Infinix Hot 30",
  "Infinix Hot 40",
  "Infinix Note 10",
  "Infinix Note 11",
  "Infinix Note 12",
  "Infinix Note 30",
  "Infinix Note 40",
  "Infinix Smart 5",
  "Infinix Smart 6",
  "Infinix Smart 7",
  "Infinix Smart 8",
  "Infinix Zero 5",
  "Infinix Zero 20",
  "Infinix Zero 30",
  // Tecno
  "Tecno Spark 6",
  "Tecno Spark 7",
  "Tecno Spark 8",
  "Tecno Spark 9",
  "Tecno Spark 10",
  "Tecno Spark 20",
  "Tecno Camon 17",
  "Tecno Camon 18",
  "Tecno Camon 19",
  "Tecno Camon 20",
  "Tecno Camon 30",
  "Tecno Pova 3",
  "Tecno Pova 4",
  "Tecno Pova 5",
  "Tecno Pova 6",
  "Tecno Pop 5",
  "Tecno Pop 6",
  "Tecno Pop 7",
  // LG
  "LG G4",
  "LG G5",
  "LG G6",
  "LG G7",
  "LG G8",
  "LG V30",
  "LG V40",
  "LG V50",
  "LG K40",
  "LG K50",
  "LG K51",
  "LG K61",
  "LG K71",
  "LG Stylo 5",
  "LG Stylo 6",
  // Sony
  "Sony Xperia 1",
  "Sony Xperia 1 II",
  "Sony Xperia 1 III",
  "Sony Xperia 1 IV",
  "Sony Xperia 1 V",
  "Sony Xperia 5",
  "Sony Xperia 5 II",
  "Sony Xperia 5 III",
  "Sony Xperia 5 IV",
  "Sony Xperia 5 V",
  "Sony Xperia 10",
  "Sony Xperia 10 II",
  "Sony Xperia 10 III",
  "Sony Xperia 10 IV",
  "Sony Xperia 10 V",
  "Sony Xperia XZ2",
  "Sony Xperia XZ3",
  // HTC
  "HTC Desire 12",
  "HTC Desire 12+",
  "HTC Desire 19s",
  "HTC Desire 20 Pro",
  "HTC Desire 21 Pro",
  "HTC Desire 22 Pro",
  "HTC U11",
  "HTC U11+",
  "HTC U12+",
  "HTC U19e",
  "HTC Exodus 1",
  // Asus
  "Asus Zenfone 7",
  "Asus Zenfone 8",
  "Asus Zenfone 9",
  "Asus Zenfone 10",
  "Asus Zenfone 11",
  "Asus ROG Phone 5",
  "Asus ROG Phone 6",
  "Asus ROG Phone 7",
  "Asus ROG Phone 8",
  "Asus ROG Phone 9",
  // Nothing
  "Nothing Phone 1",
  "Nothing Phone 2",
  "Nothing Phone 2a",
  // Generic fallbacks (never block a manual entry)
  "Android device (generic)",
  "Android tablet (generic)",
];

/**
 * Return a fresh copy of the curated model registry. The UI always allows
 * manual entry regardless of this list.
 */
export function listKnownModels(): string[] {
  return [...KNOWN_MODELS];
}
